#!/usr/bin/env -S deno run --allow-all

/**
 * This script serves as an entry point for the Deno application.
 * It forwards all arguments to the main.ts script.
 */

// Get the current Deno executable path
const denoExecutable = Deno.execPath();

// Create a command to run main.ts with the same arguments
const command = new Deno.Command(denoExecutable, {
  args: [
    "run",
    "--allow-all",
    ".deno-kit/main.ts",
    ...Deno.args,
  ],
  stdout: "inherit",
  stderr: "inherit",
});

// Run the command and wait for it to complete
const process = command.spawn();

// Exit with the same code as the child process
const status = await process.status;
Deno.exit(status.code);
